---
- name: echo var test
  hosts: all

  tasks:
  - name: print var
    #shell: echo hello
    shell: echo "{{ my_var }}"
    
    register: myVarOutput

  - debug: 
      var: myVarOutput.stdout
      verbosity: 3
